const matchesData = {
    shalay: [
{
    home: 'Arsenal',
    away: 'Coventry City',
    homeScore: 3,
    awayScore: 0,
    league: 'Premier League',
    status: 'Finished',
    statusClass: 'status-finished',
    overlayText: 'Watch Live',
    url: 'watch-live3.html',
    displayTime: '22:00',
    matchDate: '2026-08-21',
    id: '2026107'
}
    ],

    maanta: [
{
    home: 'Hull City',
    away: 'Manchester United',
    homeScore: 0,
    awayScore: 0,
    league: 'Premier League',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live.html',
    displayTime: '14:30',
    matchDate: '2026-08-22',
    id: '2026108'
},
{
    home: 'Everton',
    away: 'Crystal Palace',
    homeScore: 0,
    awayScore: 0,
    league: 'Premier League',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live1.html',
    displayTime: '17:00',
    matchDate: '2026-08-22',
    id: '2026109'
},
{
    home: 'Ipswich Town',
    away: 'Sunderland',
    homeScore: 0,
    awayScore: 0,
    league: 'Premier League',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live2.html',
    displayTime: '17:00',
    matchDate: '2026-08-22',
    id: '2026110'
},
{
    home: 'Nottingham Forest',
    away: 'Leeds United',
    homeScore: 0,
    awayScore: 0,
    league: 'Premier League',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live3.html',
    displayTime: '17:00',
    matchDate: '2026-08-22',
    id: '2026111'
},
{
    home: 'Brentford',
    away: 'Tottenham Hotspur',
    homeScore: 0,
    awayScore: 0,
    league: 'Premier League',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live.html',
    displayTime: '19:30',
    matchDate: '2026-08-22',
    id: '2026112'
},
{
    home: 'Athletic Club',
    away: 'Sevilla',
    homeScore: 0,
    awayScore: 0,
    league: 'La Liga',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live2.html',
    displayTime: '18:00',
    matchDate: '2026-08-22',
    id: '2026113'
},
{
    home: 'Espanyol',
    away: 'Real Madrid',
    homeScore: 0,
    awayScore: 0,
    league: 'La Liga',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live3.html',
    displayTime: '22:30',
    matchDate: '2026-08-22',
    id: '2026114'
},
{
    home: 'Inter Milan',
    away: 'AC Monza',
    homeScore: 0,
    awayScore: 0,
    league: 'Serie A',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live2.html',
    displayTime: '19:30',
    matchDate: '2026-08-22',
    id: '2026121'
},
{
    home: 'Genoa',
    away: 'Napoli',
    homeScore: 0,
    awayScore: 0,
    league: 'Serie A',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live3.html',
    displayTime: '21:45',
    matchDate: '2026-08-22',
    id: '2026122'
},
{
    home: 'Borussia Dortmund',
    away: 'Bayern Munich',
    homeScore: 0,
    awayScore: 0,
    league: 'Super Cup Final',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live.html',
    displayTime: '21:30',
    matchDate: '2026-08-22',
    id: '2026123'
}
    ],

    berri: [
{
    home: 'Brighton',
    away: 'Aston Villa',
    homeScore: 0,
    awayScore: 0,
    league: 'Premier League',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live.html',
    displayTime: '16:00',
    matchDate: '2026-08-24',
    id: '2026115'
},
{
    home: 'Manchester City',
    away: 'AFC Bournemouth',
    homeScore: 0,
    awayScore: 0,
    league: 'Premier League',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live1.html',
    displayTime: '16:00',
    matchDate: '2026-08-24',
    id: '2026116'
},
{
    home: 'Newcastle United',
    away: 'Liverpool',
    homeScore: 0,
    awayScore: 0,
    league: 'Premier League',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live2.html',
    displayTime: '18:30',
    matchDate: '2026-08-24',
    id: '2026117'
},
{
    home: 'Atletico Madrid',
    away: 'Villarreal',
    homeScore: 0,
    awayScore: 0,
    league: 'La Liga',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live3.html',
    displayTime: '18:00',
    matchDate: '2026-08-24',
    id: '2026118'
},
{
    home: 'Elche',
    away: 'Barcelona',
    homeScore: 0,
    awayScore: 0,
    league: 'La Liga',
    status: 'Upcoming',
    statusClass: 'status-upcoming',
    overlayText: 'Watch Live',
    url: 'watch-live1.html',
    displayTime: '22:30',
    matchDate: '2026-08-24',
    id: '2026120'
}
    ]
};